# Copyright (c) 2026 hangtiancheng
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Swifty

[buildPlans.Swifty]
exportGlyphNames = false
family = "Swifty"
noCvSs = true
serifs = "sans"
spacing = "normal"

[buildPlans.Swifty.variants]
inherits = "ss06"

[buildPlans.Swifty.variants.design]
at = "compact"
capital-g = "toothed-serifless-hookless"
capital-j = "serifless"
capital-m = "flat-bottom-serifless"
capital-q = "crossing"
capital-w = "straight-flat-top-serifless"
diacritic-dot = "round"
five = "upright-arched-serifless"
j = "serifless"
lig-ltgteq = "slanted"
punctuation-dot = "round"
tittle = "round"
two = "straight-neck-serifless"
w = "straight-flat-top-serifless"

[buildPlans.Swifty.ligations]
inherits = "javascript"

[buildPlans.Swifty.weights.Regular]
css = 400
menu = 400
shape = 400

[buildPlans.Swifty.weights.Bold]
css = 700
menu = 700
shape = 700

[buildPlans.Swifty.slopes.Upright]
angle = 0
css = "normal"
menu = "upright"
shape = "upright"

[buildPlans.Swifty.slopes.Italic]
angle = 9.4
css = "italic"
menu = "italic"
shape = "italic"
